name: Github Actions 이용하여 배포하기

on:
  push:
    branches:
      - main
env:
  EC2_HOST: ${{secretes.EC2_HOST}}
  EC2_USERNAME: ${{secretes.EC2_USERNAME}}
  EC2_PRIVATE_KEY: ${{secretes.EC2_PRIVATE_KEY}}
  DEPLOY_PATH: /var/www/html
jobs:
  code-fetch-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: EC2_HOST
          username: EC2_USERNAME
          key: EC_PRIVATE_KEY
          script: |
            cd /home/ubuntu/cicd_test
            ls -al
